### ISSUE TITLE
Early cascade injection

### ISSUE THREAD

**Issue by Kibouo** [Offensive-Panda/ProcessInjectionTechniques#2]
A new technique was recently published. Could it be included?
- https://www.outflank.nl/blog/2024/10/15/introducing-early-cascade-injection-from-windows-process-creation-to-stealthy-injection/
- https://github.com/Cracked5pider/earlycascade-injection?tab=readme-ov-file

**Comment by Offensive-Panda** [comment]
> A new technique was recently published. Could it be included?
> - https://www.outflank.nl/blog/2024/10/15/introducing-early-cascade-injection-from-windows-process-creation-to-stealthy-injection/
> - https://github.com/Cracked5pider/earlycascade-injection?tab=readme-ov-file

Hi, yes, some of the new techniques are in my to-do list, like cascade injection and hookchain. Currently, I am working on another project, but soon it will be added to the series. Thank you for mentioning this.
